sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: admin
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRXdVo1QvtgQPrqSAz3
    access-key-secret: L3oWMEM6TtIxkRWSUf4Nm0rr6C9wdK
    bucket-name: web-kang
